### PR TITLE
Make ROCM platform name consistent with tensorflow stream executor.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
This will enable the //tensorflow/compiler/xla/service/gpu:custom_call_test unit test to work with BEF Thunk on ROCM.

Thanks for your contribution! Unfortunately, tensorflow/runtime is currently not
accepting contributions. Please see the
[Contribution Guidelines](../blob/master/README.md#contribution-guidelines) for
more information.

/cc @chsigg

### CODE REVIEW

**Comment by chsigg** [comment]
Would you mind explaining briefly why/where we are string-matching the TFRT GPU platform name in XLA?

**Comment by rsanthanam-amd** [comment]
This enables the custom call test for BEF Thunk on ROCm.

The platform name is used as one of the keys for registry and lookup in the custom call registry.

In this case, the custom call function is registered in TF proper with the 'ROCM' platform name.

But it is retrieved in TFRT using 'ROCm' and because of this, the lookup fails.

**Comment by chsigg** [comment]
Rohit, I think https://github.com/tensorflow/tensorflow/commit/5cb5f52 has fixed this issue. Would you mind to confirm and close? Thanks!

**Comment by rsanthanam-amd** [comment]
Confirmed that the cited fix resolves the issue.

**Pull request closed without merging**
